### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by kusumlata123** [boberle/corefconversion#3]
assert sent_start == sent_stop
AssertionError
ython3 jsonlines2conll.py -g testing/test.hindi.jsonlines -o ouput.conll
Traceback (most recent call last):
  File "jsonlines2conll.py", line 156, in <module>
    main()
  File "jsonlines2conll.py", line 145, in main
    jsonlines2conll(
  File "jsonlines2conll.py", line 88, in jsonlines2conll
    conll_transform.textpos2sentpos(mentions, sents)
  File "/home/dr/Desktop/corefconversion-master/conll_transform.py", line 274, in textpos2sentpos
    assert sent_start == sent_stop
AssertionError

**Comment by xiulinyang** [comment]
It means the mention spans over 2 sentences. You might need to check if your sentence segmentation or mention span is correct or not.

**Comment by boberle** [comment]
Indeed. The assumption of all the formats in this repository is that each mention must be contained in a sentence, and can't span over several sentences.
